apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bmw-tls
spec:
  secretName: bmw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
