apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bmw
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: bmw
          port: 5000
  tls:
    secretName: bmw-tls
