image:
  repository: ghcr.io/semtexkg/e36-service
  tag: latest
  pullPolicy: IfNotPresent

data:
  hostPath: /opt/k3s/bmw

ingress:
  host: bmw.k-labs.app

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
